const examples=[
 {id:'circle',name:'Circle: glue interval endpoints',word:'No 2-cell relation',generators:['a'],group:'⟨ a | — ⟩ ≅ ℤ',description:'Identifying the two ends turns one edge into a loop.',explanation:'One loop and no filling relation gives the infinite cyclic group.'},
 {id:'wedge',name:'Figure eight: wedge two circles',word:'No 2-cell relation',generators:['a','b'],group:'⟨ a, b | — ⟩ ≅ F₂',description:'Two circles share a single basepoint.',explanation:'Two independent loops generate the free group on two generators.'},
 {id:'torus',name:'Torus: opposite sides of a square',word:'a b a⁻¹ b⁻¹',generators:['a','b'],group:'⟨ a, b | aba⁻¹b⁻¹ = 1 ⟩ ≅ ℤ²',description:'Opposite edges are glued with matching orientations.',explanation:'The boundary relation says ab = ba, so the two loops commute.'},
 {id:'klein',name:'Klein bottle: twisted square gluing',word:'a b a⁻¹ b',generators:['a','b'],group:'⟨ a, b | aba⁻¹ = b⁻¹ ⟩',description:'One pair of opposite edges is glued with a twist.',explanation:'Traveling around a reverses the direction of the b loop.'},
 {id:'projective',name:'Projective plane: glue with a twist',word:'a a',generators:['a'],group:'⟨ a | a² = 1 ⟩ ≅ ℤ/2ℤ',description:'The disk boundary traverses the same edge twice.',explanation:'The generator has order two.'}
];
const $=s=>document.querySelector(s),select=$('#example'),buttons=$('#generator-buttons');
const canvas=$('#diagram'),ctx=canvas.getContext('2d'),glue=$('#gluing-diagram'),gx=glue.getContext('2d');
let current=examples[2],selected='a',animating=false,trace=0,wordSteps=['a','b'],enteredSteps=['a','b'],simplifiedSteps=null,homotopyAnimating=false,homotopyProgress=0,homotopyRun=0;
const deform={a:{size:0,shift:0},b:{size:0,shift:0}},view={yaw:-.72,pitch:.52,scale:82,cx:450,cy:315};
const colors={a:'#315bc7',b:'#ec604f',selected:'#e7b341'};
examples.forEach(x=>select.add(new Option(x.name,x.id)));select.value='torus';

function arrow(x1,y1,x2,y2,color,label){const a=Math.atan2(y2-y1,x2-x1),mx=(x1+x2)/2,my=(y1+y2)/2;gx.strokeStyle=gx.fillStyle=color;gx.lineWidth=9;gx.lineCap='round';gx.beginPath();gx.moveTo(x1,y1);gx.lineTo(x2,y2);gx.stroke();gx.save();gx.translate(mx,my);gx.rotate(a);gx.beginPath();gx.moveTo(15,0);gx.lineTo(-9,-9);gx.lineTo(-9,9);gx.closePath();gx.fill();gx.restore();gx.font='italic 700 34px Georgia';gx.fillText(label,mx+(Math.abs(y2-y1)>20?22:-5),my+(Math.abs(x2-x1)>20?-18:8))}
function emptyMessage(context,w,h,line){context.fillStyle='#6f7180';context.textAlign='center';context.font='500 24px Georgia';context.fillText(line,w/2,h/2);context.font='16px system-ui';context.fillText('Choose “Torus” to use the model we are developing first.',w/2,h/2+34);context.textAlign='start'}
function pathArrow(context,p1,p2,label){const a=Math.atan2(p2.y-p1.y,p2.x-p1.x),x=(p1.x+p2.x)/2,y=(p1.y+p2.y)/2;context.save();context.translate(x,y);context.rotate(a);context.fillStyle=colors.selected;context.strokeStyle='white';context.lineWidth=2;context.beginPath();context.moveTo(13,0);context.lineTo(-8,-8);context.lineTo(-8,8);context.closePath();context.fill();context.stroke();context.restore();context.fillStyle='#1f2230';context.font='700 13px system-ui';context.textAlign='center';context.fillText(label,x,y-15);context.textAlign='start'}
function polygonWordSegment(i,l,r,t,b){const token=wordSteps[i],g=token.toLowerCase(),forward=token===g,offset=((i%5)-2)*5,p1=g==='a'?{x:forward?l:r,y:(t+b)/2+offset}:{x:(l+r)/2+offset,y:forward?b:t},p2=g==='a'?{x:forward?r:l,y:(t+b)/2+offset}:{x:(l+r)/2+offset,y:forward?t:b};return{p1,p2}}
function traceDot(context,p){context.beginPath();context.arc(p.x,p.y,9,0,Math.PI*2);context.fillStyle='white';context.fill();context.strokeStyle='#1f2230';context.lineWidth=3;context.stroke()}
function drawPolygonWord(l,r,t,b){wordSteps.forEach((token,i)=>{const {p1,p2}=polygonWordSegment(i,l,r,t,b);gx.strokeStyle='#1f2230';gx.lineWidth=12;gx.beginPath();gx.moveTo(p1.x,p1.y);gx.lineTo(p2.x,p2.y);gx.stroke();gx.strokeStyle=colors.selected;gx.lineWidth=7;gx.stroke();pathArrow(gx,p1,p2,String(i+1))});if(animating&&wordSteps.length){const scaled=trace*wordSteps.length,i=Math.min(wordSteps.length-1,Math.floor(scaled)),q=scaled-i,{p1,p2}=polygonWordSegment(i,l,r,t,b);traceDot(gx,{x:p1.x+(p2.x-p1.x)*q,y:p1.y+(p2.y-p1.y)*q})}}
function drawGluing(){gx.clearRect(0,0,glue.width,glue.height);gx.fillStyle='#faf8f3';gx.fillRect(0,0,glue.width,glue.height);if(current.id!=='torus'){emptyMessage(gx,glue.width,glue.height,'This gluing diagram is coming next.');return}const l=250,r=650,t=55,b=395;gx.fillStyle='#315bc710';gx.fillRect(l,t,r-l,b-t);gx.strokeStyle='#1f2230';gx.lineWidth=2;gx.strokeRect(l,t,r-l,b-t);arrow(l+35,b,r-35,b,colors.a,'a');arrow(l+35,t,r-35,t,colors.a,'a');arrow(l,b-30,l,t+30,colors.b,'b');arrow(r,b-30,r,t+30,colors.b,'b');drawPolygonWord(l,r,t,b);gx.fillStyle='#1f2230';[[l,t],[r,t],[l,b],[r,b]].forEach(([x,y])=>{gx.beginPath();gx.arc(x,y,8,0,Math.PI*2);gx.fill()});gx.fillStyle='#6f7180';gx.font='15px system-ui';gx.textAlign='center';gx.fillText('Blue and red arrows are fixed gluing instructions; gold is the entered path.',450,442);gx.textAlign='start'}

function project(u,v){const R=2.05,r=.83,x=(R+r*Math.cos(v))*Math.cos(u),y=(R+r*Math.cos(v))*Math.sin(u),z=r*Math.sin(v),cy=Math.cos(view.yaw),sy=Math.sin(view.yaw),cp=Math.cos(view.pitch),sp=Math.sin(view.pitch),xx=x*cy-y*sy,yy=x*sy+y*cy,py=yy*cp-z*sp,pz=yy*sp+z*cp;return{x:view.cx+xx*view.scale,y:view.cy-py*view.scale,z:pz}}
function loopPoint(g,t){const d=deform[g],wave=d.size*Math.sin(Math.PI*2*t+d.shift);return g==='a'?project(Math.PI*2*t,.12+wave):project(.12+wave,Math.PI*2*t)}
function stroke(points,color,width){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);points.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke()}
function torusWordPoint(progress){const scaled=progress*wordSteps.length,i=Math.min(wordSteps.length-1,Math.floor(scaled)),q=scaled-i,token=wordSteps[i],g=token.toLowerCase(),dir=token===g?1:-1;return project(.12+(g==='a'?dir*Math.PI*2*q:0),.12+(g==='b'?dir*Math.PI*2*q:0))}
function wordLiftPoint(steps,progress){if(!steps.length)return{u:.12,v:.12};const scaled=Math.min(progress,1-.000001)*steps.length,index=Math.floor(scaled),q=scaled-index;let u=.12,v=.12;for(let i=0;i<index;i++){const token=steps[i],dir=token===token.toLowerCase()?1:-1;if(token.toLowerCase()==='a')u+=dir*Math.PI*2;else v+=dir*Math.PI*2}const token=steps[index],dir=token===token.toLowerCase()?1:-1;if(token.toLowerCase()==='a')u+=dir*Math.PI*2*q;else v+=dir*Math.PI*2*q;return{u,v}}
function torusPath(steps){const points=[];for(let i=0;i<=320;i++){const p=wordLiftPoint(steps,i/320);points.push(project(p.u,p.v))}return points}
function drawHomotopyOnTorus(){const eased=homotopyProgress<.5?4*homotopyProgress**3:1-((-2*homotopyProgress+2)**3)/2,start=torusPath(enteredSteps),end=torusPath(simplifiedSteps),middle=start.map((p,i)=>{const a=wordLiftPoint(enteredSteps,i/320),b=wordLiftPoint(simplifiedSteps,i/320);return project(a.u+(b.u-a.u)*eased,a.v+(b.v-a.v)*eased)});ctx.save();ctx.globalAlpha=.18;stroke(start,colors.selected,5);stroke(end,'#4da66a',5);ctx.restore();stroke(middle,'#1f2230',14);stroke(middle,colors.selected,8);traceDot(ctx,middle[Math.min(320,Math.round(homotopyProgress*320))])}
function drawWordOnTorus(){if(homotopyAnimating){drawHomotopyOnTorus();return}let u=.12,v=.12;wordSteps.forEach((token,i)=>{const g=token.toLowerCase(),dir=token===g?1:-1,points=[];for(let j=0;j<=70;j++){const q=j/70;points.push(project(u+(g==='a'?dir*Math.PI*2*q:0),v+(g==='b'?dir*Math.PI*2*q:0)))}stroke(points,'#1f2230',14);stroke(points,colors.selected,8);pathArrow(ctx,points[30],points[38],String(i+1));if(g==='a')u+=dir*Math.PI*2;else v+=dir*Math.PI*2});if(animating&&wordSteps.length)traceDot(ctx,torusWordPoint(trace))}
function drawTorus(){const rings=[];for(let i=0;i<34;i++){const v=Math.PI*2*i/34,points=[];for(let j=0;j<=80;j++)points.push(project(Math.PI*2*j/80,v));rings.push({z:points.reduce((n,p)=>n+p.z,0)/points.length,points})}rings.sort((a,b)=>a.z-b.z).forEach(r=>stroke(r.points,r.z>0?'#96a9d5':'#c5cede',r.z>0?6:3));for(let i=0;i<16;i++){const points=[];for(let j=0;j<=40;j++)points.push(project(Math.PI*2*i/16,Math.PI*2*j/40));stroke(points,'#e5e8ee',1.5)}['a','b'].forEach(g=>{const points=[];for(let j=0;j<=180;j++)points.push(loopPoint(g,j/180));stroke(points,colors[g],g===selected?10:6)});drawWordOnTorus();ctx.font='italic 700 28px Georgia';['a','b'].forEach(g=>{const p=loopPoint(g,.6);ctx.fillStyle=colors[g];ctx.fillText(g,p.x+13,p.y-10)})}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#faf8f3';ctx.fillRect(0,0,canvas.width,canvas.height);current.id==='torus'?drawTorus():emptyMessage(ctx,canvas.width,canvas.height,'The interactive surface is currently focused on the torus.')}
function status(){const element=$('#homotopy-status');if(!element)return;const d=deform[selected];element.textContent=`Loop class [${selected}] is unchanged · deformation ${Math.round(Math.abs(d.size)/.9*100)}%`}
function updateButtons(){[...buttons.children].forEach((b,i)=>b.classList.toggle('active',current.generators[i]===selected))}
function load(){current=examples.find(x=>x.id===select.value);selected=current.generators[0];$('#word').textContent=current.word;$('#group').textContent=current.group;$('#gluing-description').textContent=current.description;$('#explanation').textContent=current.explanation;$('#surface-title').textContent=current.id==='torus'?'Torus with generator cycles':'The glued space';buttons.innerHTML='';current.generators.forEach(g=>{const b=document.createElement('button');b.textContent=`generator ${g}`;b.onclick=()=>{selected=g;updateButtons();status();drawGluing();draw()};buttons.append(b)});updateButtons();status();drawGluing();draw()}
function frame(){if(!animating)return;trace+=.008;if(trace>=1){trace=0;animating=false;$('#animate').textContent='▶ Trace group element'}drawGluing();draw();if(animating)requestAnimationFrame(frame)}
$('#animate').onclick=()=>{if(animating||homotopyAnimating||current.id!=='torus'||!wordSteps.length)return;animating=true;trace=0;$('#animate').textContent='Tracing group element…';requestAnimationFrame(frame)};
select.addEventListener('change',load);load();

function parseWord(raw){const source=raw.replaceAll('⁻¹','^-1').replaceAll('−','-').replace(/\s+/g,''),steps=[];if(!source)return{steps};const token=/([abAB])(?:\^(-?\d+))?/gy;let position=0,match;while(position<source.length){token.lastIndex=position;match=token.exec(source);if(!match)return{error:'Use only a, b, and integer powers such as a^-1.'};position=token.lastIndex;const base=match[1].toLowerCase(),baseDirection=match[1]===base?1:-1,power=match[2]===undefined?1:Number(match[2]),count=Math.abs(power);if(!Number.isSafeInteger(power)||count>24||steps.length+count>24)return{error:'Please keep the expanded word to 24 letters or fewer.'};const direction=baseDirection*Math.sign(power);for(let i=0;i<count;i++)steps.push(direction<0?base.toUpperCase():base)}return{steps}}
function exponent(steps,g){return steps.reduce((sum,token)=>sum+(token===g?1:token===g.toUpperCase()?-1:0),0)}
function canonicalSteps(steps){const result=[],a=exponent(steps,'a'),b=exponent(steps,'b');for(let i=0;i<Math.abs(a);i++)result.push(a<0?'A':'a');for(let i=0;i<Math.abs(b);i++)result.push(b<0?'B':'b');return result}
function powerLabel(g,n){if(!n)return'';return Math.abs(n)===1?(n<0?`${g}⁻¹`:g):`${g}${n<0?'⁻':''}${Math.abs(n)}`}
function canonicalLabel(steps){return powerLabel('a',exponent(steps,'a'))+powerLabel('b',exponent(steps,'b'))||'1'}
function resetSimplification(){homotopyRun++;simplifiedSteps=null;homotopyAnimating=false;homotopyProgress=0;$('#simplification').hidden=true;$('#show-homotopy').hidden=true;$('#show-homotopy').disabled=false;$('#show-homotopy').textContent='Show homotopy'}
$('#word-form').addEventListener('submit',e=>{e.preventDefault();const result=parseWord($('#group-word').value),help=$('#word-help');if(result.error){help.textContent=result.error;help.classList.add('error');return}animating=false;trace=0;$('#animate').textContent='▶ Trace group element';enteredSteps=result.steps;wordSteps=[...enteredSteps];resetSimplification();help.textContent=wordSteps.length?`Drawing ${wordSteps.length} directed segment${wordSteps.length===1?'':'s'} in gold.`:'The identity element is the constant loop.';help.classList.remove('error');drawGluing();draw()});
$('#simplify').onclick=()=>{const input=$('#group-word'),result=parseWord(input.value),help=$('#word-help');if(result.error){help.textContent=result.error;help.classList.add('error');return}resetSimplification();enteredSteps=result.steps;wordSteps=[...enteredSteps];simplifiedSteps=canonicalSteps(enteredSteps);const box=$('#simplification');box.textContent=`${input.value.trim()||'1'}  ≃  ${canonicalLabel(enteredSteps)}`;box.hidden=false;$('#show-homotopy').hidden=false;help.classList.remove('error');drawGluing();draw()};
$('#show-homotopy').onclick=()=>{if(!simplifiedSteps||homotopyAnimating)return;animating=false;wordSteps=[...enteredSteps];homotopyAnimating=true;homotopyProgress=0;const run=++homotopyRun,button=$('#show-homotopy'),box=$('#simplification'),label=`${$('#group-word').value.trim()||'1'}  ≃  ${canonicalLabel(enteredSteps)}`,started=performance.now(),duration=6000;button.disabled=true;function homotopyFrame(now){if(run!==homotopyRun)return;homotopyProgress=Math.min(1,(now-started)/duration);box.textContent=`${label}  ·  homotopy ${Math.round(homotopyProgress*100)}%`;draw();if(homotopyProgress<1){requestAnimationFrame(homotopyFrame);return}homotopyAnimating=false;wordSteps=[...simplifiedSteps];box.textContent=`${label}  ·  simplified`;button.disabled=false;button.textContent='Show homotopy again';drawGluing();draw()}requestAnimationFrame(homotopyFrame)};
